version: '3.7'
services:
  jenkins:
    build:
      context: ./docker/common/jenkins
    ports:
      - "8000:8080"
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - docker-certs:/certs/client:ro
      - /root/.ssh:/jenkins/.ssh
    depends_on:
      - docker
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - docker-data:/var/lib/docker

volumes:
  jenkins-data:
  docker-certs:
  docker-data: